### ISSUE TITLE
Provide example configuration

### ISSUE THREAD

**Issue by mattijsf** [stas-demydiuk/domoticz-dashboard#1]
Hi I'd like to give this dashboard a try and see If I can help development If I like it. I added the required `server.json` with domoticz and mqtt config. I think I need to configure `dashboard.json` but I wondered if you maybe have a sample configuration available that I can tweak / customize to get started.

**Comment by stas-demydiuk** [comment]
This should be enough to start application (dashboard.json):
`[
{
"roomId":0,
"widgets":[]
}
]`
After start you will be able to add widgets using UI interface:
click "cog" icon in the header, then "Add widget" button
